name: assignment2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - jupyter
  - ipykernel
  - ruff
  - black
  - mypy
  - pytest

